language: node_js
node_js:
- '6'
before_install:
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos.js
env:
  secure: "m4gnqny4YTzWgSEk/z8rsFd0CotCZOD/Ws3Q0FZaYnoGi+aahXgE64DJQspStXi7+5/xBENCYNK+SuRIZHfUHrFvb9jGH52v6s9TuJJvFOV4dV2F986SLwOeGtshuXhpUz9HOttkuSDQi+JFd2D81EFCBwiWfbUJcIoNef3R0xyGUbaASpYSn7kg/i9sdOSftgu13hdtd4SNcxC07Euja6GTK1QTDUT0XSEUg3Qdzx4wtzTbinB1J6RRAQCscphoaGv7k2K4/70sBo8/M+BDdb/NZjsbyV9FMWG3N92f6T+z1UZ4wrUseIq/xICQ5Fb8F7qgbRL42aPIWP0zIIZNz4/UTocb6YOJTHcO6eRimUapK/Np+e7WZn2XCh2i6TT6E7B/V11SdMoHhmxStPV6D6tAvtIa1aShtWt6O4OApLJ8l16gOwaxMWROdbeCA59v+Yo6uhbBCd/AW7PvVrZp2foJm0dsDrxmbThWD47V5+lv9vL11pmo4p6XajIDPPaZjLAlH2+S8QQ01fxsvO1jwRctY2bnxwhlp8gDLKBIQGxi4lQT54ntERGc15hdSVMoDr1UXgavlzkPz07ZvGi9kWFWYDnx99mfvOOn7dEoXhv2sIDG49uOQkggTeG3lQnHZkf8Y6xWpIn4o0G5VjAfGMkLR/A5hhovi12yfp8AI4E="